/** Role names — single source of truth, mirrored in seed data. */
export const ROLES = {
  EMPLOYEE: "EMPLOYEE",
  IT_SUPPORT: "IT_SUPPORT",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
} as const;
export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_NAMES: RoleName[] = Object.values(ROLES);

/** Fine-grained permissions (spec §8). */
export const PERMISSIONS = {
  TICKET_CREATE: "ticket:create",
  TICKET_READ_OWN: "ticket:read:own",
  TICKET_READ_ASSIGNED: "ticket:read:assigned",
  TICKET_READ_TEAM: "ticket:read:team",
  TICKET_READ_ALL: "ticket:read:all",
  TICKET_UPDATE: "ticket:update",
  TICKET_UPDATE_OWN: "ticket:update:own",
  TICKET_RESOLVE: "ticket:resolve",
  TICKET_RESOLVE_OWN: "ticket:resolve:own",
  TICKET_CLOSE: "ticket:close",
  TICKET_ASSIGN: "ticket:assign",
  TICKET_COMMENT: "ticket:comment",
  TICKET_COMMENT_OWN: "ticket:comment:own",
  TICKET_DELETE: "ticket:delete",
  ASSET_READ_OWN: "asset:read:own",
  ASSET_READ_ALL: "asset:read:all",
  ASSET_MANAGE: "asset:manage",
  REPORT_READ: "report:read",
  USER_MANAGE: "user:manage",
  ROLE_MANAGE: "role:manage",
  PERMISSION_MANAGE: "permission:manage",
  CATEGORY_MANAGE: "category:manage",
  SLA_MANAGE: "sla:manage",
  AUDIT_READ: "audit:read",
  SECURITY_MANAGE: "security:manage",
  NOTIFICATION_READ_OWN: "notification:read:own",
} as const;
export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Role → permissions mapping used by the seed. */
export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  EMPLOYEE: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ_OWN,
    PERMISSIONS.TICKET_UPDATE_OWN,
    PERMISSIONS.TICKET_RESOLVE_OWN,
    PERMISSIONS.TICKET_COMMENT_OWN,
    PERMISSIONS.ASSET_READ_OWN,
    PERMISSIONS.NOTIFICATION_READ_OWN,
  ],
  IT_SUPPORT: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ_ASSIGNED,
    PERMISSIONS.TICKET_READ_ALL,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_RESOLVE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_COMMENT,
    PERMISSIONS.ASSET_READ_ALL,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.NOTIFICATION_READ_OWN,
  ],
  MANAGER: [
    PERMISSIONS.TICKET_READ_TEAM,
    PERMISSIONS.TICKET_READ_ALL,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.NOTIFICATION_READ_OWN,
  ],
  ADMIN: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ_ALL,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_RESOLVE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_COMMENT,
    PERMISSIONS.TICKET_DELETE,
    PERMISSIONS.ASSET_READ_ALL,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.PERMISSION_MANAGE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.SLA_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.NOTIFICATION_READ_OWN,
  ],
};

export const TICKET_STATUSES = ["OPEN", "ASSIGNED", "IN_PROGRESS", "PENDING", "RESOLVED", "CLOSED"] as const;
export type TicketStatus = (typeof TICKET_STATUSES)[number];

export const TICKET_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"] as const;
export type TicketPriority = (typeof TICKET_PRIORITIES)[number];

/** Valid status transitions — the backend owns these (spec §10). */
export const TICKET_TRANSITIONS: Record<TicketStatus, TicketStatus[]> = {
  OPEN: ["ASSIGNED", "IN_PROGRESS", "RESOLVED", "CLOSED"],
  ASSIGNED: ["IN_PROGRESS", "PENDING", "RESOLVED", "CLOSED"],
  IN_PROGRESS: ["PENDING", "RESOLVED", "CLOSED"],
  PENDING: ["IN_PROGRESS", "RESOLVED", "CLOSED"],
  RESOLVED: ["CLOSED", "IN_PROGRESS"], // reopen before confirmation
  CLOSED: [],
};

export const ASSET_STATUSES = ["AVAILABLE", "ASSIGNED", "MAINTENANCE", "RETURNED", "RETIRED"] as const;
export type AssetStatus = (typeof ASSET_STATUSES)[number];

export const ASSET_TRANSITIONS: Record<AssetStatus, AssetStatus[]> = {
  AVAILABLE: ["ASSIGNED", "MAINTENANCE", "RETIRED"],
  ASSIGNED: ["RETURNED", "MAINTENANCE"],
  MAINTENANCE: ["AVAILABLE", "RETIRED"],
  RETURNED: ["AVAILABLE", "RETIRED"],
  RETIRED: [],
};

export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET: "PASSWORD_RESET",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  ROLE_CHANGED: "ROLE_CHANGED",
  PERMISSION_CHANGED: "PERMISSION_CHANGED",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_UPDATED: "TICKET_UPDATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  TICKET_DELETED: "TICKET_DELETED",
  ASSET_REGISTERED: "ASSET_REGISTERED",
  ASSET_ASSIGNED: "ASSET_ASSIGNED",
  ASSET_RETURNED: "ASSET_RETURNED",
  ASSET_RETIRED: "ASSET_RETIRED",
  SLA_POLICY_CHANGED: "SLA_POLICY_CHANGED",
  ADMIN_ACTION: "ADMIN_ACTION",
} as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const SECURITY_EVENTS = {
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  TOKEN_REUSE: "TOKEN_REUSE",
  RATE_LIMITED: "RATE_LIMITED",
  AUTH_REGISTER: "AUTH_REGISTER",
  PASSWORD_RESET_USED: "PASSWORD_RESET_USED",
} as const;
export type SecurityEventType = (typeof SECURITY_EVENTS)[keyof typeof SECURITY_EVENTS];

export const NOTIFICATION_TYPES = {
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED",
  TICKET_COMMENTED: "TICKET_COMMENTED",
  SLA_WARNING: "SLA_WARNING",
  SLA_BREACH: "SLA_BREACH",
  ASSET_ASSIGNED: "ASSET_ASSIGNED",
} as const;
